install.packages("lattice")
install.packages("lme4")
install.packages("ggplot2")
install.packages("dplyr")
install.packages("tidyr")
install.packages("lmerTest")
install.packages("stargazer")
install.packages("MASS")
install.packages("MuMIn")

#install.packages("tidyverse")
#install.packages("car")
#install.packages("reshape")
#install.packages("doBy")
#install.packages("pbkrtest")
#install.packages("ggm")
#install.packages("Hmisc")
#install.packages("AICcmodavg")
